[build]
publish = "public"
command = "hugo --theme=hugo-creative-portfolio-theme --gc --minify -D"

[context.production.environment]
HUGO_VERSION = "0.92.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --theme=hugo-creative-portfolio-theme --gc --minify --enableGitInfo -D"

[context.split1.environment]
HUGO_VERSION = "0.92.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --theme=hugo-creative-portfolio-theme --gc --minify --buildFuture -b $DEPLOY_PRIME_URL -D"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.2"

[context.branch-deploy]
command = "hugo --theme=hugo-creative-portfolio-theme --gc --minify -b $DEPLOY_PRIME_URL -D"

[context.branch-deploy.environment]
HUGO_VERSION = "0.92.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200